profile : prod
server :
  port: 8100

logging:
  level:
    org.springframework : info

spring:
  messages:
    basename : messages
    fallback-to-system-locale: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: username
      password : passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"